<?php

test('subscribe form editor uses a right inspector and style picker', function () {
    $edit = file_get_contents(dirname(__DIR__, 2).'/resources/js/pages/subscribe-forms/edit.tsx');
    $view = file_get_contents(dirname(__DIR__, 2).'/resources/js/components/subscribe-form-view.tsx');
    $artwork = file_get_contents(dirname(__DIR__, 2).'/resources/js/components/subscribe-form-artwork.tsx');
    $originKitDotMatrix = file_get_contents(dirname(__DIR__, 2).'/components/originkit/ui/hero-26/dotmatrix.tsx');
    $public = file_get_contents(dirname(__DIR__, 2).'/resources/js/pages/subscribe-forms/public.tsx');

    expect($edit)->toBeString()
        ->toContain('lg:border-l')
        ->toContain('lg:w-[26rem]')
        ->toContain('h-dvh')
        ->toContain('fixed inset-0 flex h-dvh')
        ->toContain('ArrowLeft01Icon')
        ->toContain('Back to ${audience.name}')
        ->not->toContain('SubscribeFormEditorLayout')
        ->toContain('lg:overflow-y-auto')
        ->toContain('className="p-4 sm:p-5"')
        ->toContain('gap-x-3 gap-y-2 border-b bg-background')
        ->toContain('id="subscribe-form-editor"')
        ->toContain('form="subscribe-form-editor"')
        ->toContain('data-test="subscribe-form-actions"')
        ->toContain('data-test="subscribe-form-status"')
        ->not->toContain('sticky bottom-0 z-10 flex justify-end border-t bg-background')
        ->toContain('min-h-[36rem]')
        ->toContain('data-test="subscribe-form-preview"')
        ->toContain('data-test="subscribe-form-preview-toolbar"')
        ->toContain('justify-self-end')
        ->toContain('xl:col-start-2 xl:row-start-1 xl:overflow-visible')
        ->toContain('className="flex shrink-0 items-center gap-2"')
        ->not->toContain(
            'overflow-x-auto rounded-xl border bg-background p-1 shadow-xs',
        )
        ->not->toContain('absolute top-3 z-10')
        ->not->toContain('p-4 pt-16 sm:p-6 sm:pt-16')
        ->toContain('data-preview-viewport={previewViewport}')
        ->toContain('data-preview-state={previewState}')
        ->toContain('aria-label="Preview width"')
        ->toContain('aria-label="Preview state"')
        ->toContain("type PreviewViewport = 'desktop' | 'mobile';")
        ->toContain("type PreviewState = 'form' | 'success' | 'error';")
        ->toContain("completed={previewState === 'success'}")
        ->toContain("previewState === 'error'")
        ->toContain('lg:overflow-y-auto')
        ->toContain(
            'lg:max-w-none lg:overflow-y-auto lg:rounded-none lg:border-0 lg:shadow-none',
        )
        ->toContain('data-test={`subscribe-form-style-${option.value}`}')
        ->toContain('<RadioGroup')
        ->toContain('<Radio.Root')
        ->toContain('placeholder="Join our newsletter"')
        ->toContain('placeholder="Website footer"')
        ->toContain('color: form.data.brand_color')
        ->toContain('font: form.data.brand_font')
        ->toContain('form.data.brand_input_style')
        ->toContain('data-test="subscribe-form-brand-color"')
        ->toContain('data-test="subscribe-form-brand-font"')
        ->toContain('data-test="subscribe-form-brand-input-style"')
        ->toContain('function InspectorSection({')
        ->toContain('<Collapsible')
        ->toContain('<CollapsibleTrigger')
        ->toContain('<CollapsibleContent')
        ->toContain('const [open, setOpen] = useState(true);')
        ->toContain('<FieldGroup className="gap-3">')
        ->toContain('className="w-full rounded-xl border bg-card shadow-xs"')
        ->toContain('rounded-lg bg-background shadow-xs ring-1 ring-border')
        ->toContain("? 'rounded-t-xl rounded-b-none'")
        ->toContain(": 'rounded-xl',")
        ->toContain('testId="subscribe-form-section-layout"')
        ->toContain('testId="subscribe-form-section-brand-theme"')
        ->toContain('testId="subscribe-form-section-fields"')
        ->toContain('testId="subscribe-form-section-artwork"')
        ->toContain('testId="subscribe-form-section-logo"')
        ->toContain('testId="subscribe-form-section-content"')
        ->toContain('testId="subscribe-form-section-redirect"')
        ->toContain('data-test="subscribe-form-redirect-enabled"')
        ->toContain('data-test="subscribe-form-redirect-url"')
        ->toContain('Wait five seconds')
        ->toContain('data-test="subscribe-form-image-input"')
        ->toContain('const SUBSCRIBE_FORM_IMAGE_MAX_BYTES = 2 * 1024 * 1024;')
        ->toContain('file.size > SUBSCRIBE_FORM_IMAGE_MAX_BYTES')
        ->toContain("form.setError('image', 'Artwork must be 2 MB or smaller.')")
        ->toContain("form.setError('logo', 'Logo must be 2 MB or smaller.')")
        ->toContain('JPG, PNG, or WEBP up to 2 MB.')
        ->toContain('subscribeForm.image_processing')
        ->toContain('Uploads are')
        ->toContain('optimized to WebP.')
        ->toContain('data-test="subscribe-form-artwork-type"')
        ->toContain('data-test="subscribe-form-image-presets"')
        ->toContain('data-test="subscribe-form-background-presets"')
        ->toContain('handleArtworkTypeChange')
        ->toContain('value="image-preset"')
        ->toContain('value="background-preset"')
        ->toContain('<ArtworkPresetOption')
        ->toContain('usePoll(')
        ->toContain('data-test="subscribe-form-logo-input"')
        ->toContain('data-test="subscribe-form-logo-shape"')
        ->toContain('data-test="subscribe-form-logo-position"')
        ->toContain('data-test="subscribe-form-logo-size"')
        ->toContain('data-test="subscribe-form-header-spacing"')
        ->toContain('data-test="subscribe-form-card-padding"')
        ->toContain('data-test="subscribe-form-image-side"')
        ->toContain('data-test="subscribe-form-text-alignment"')
        ->toContain('logoShapeOptions')
        ->toContain('<Tooltip')
        ->toContain('<TooltipTrigger')
        ->toContain('<TooltipContent>')
        ->toContain('aria-label={')
        ->toContain('option.label')
        ->toContain('flex h-11 min-w-0 cursor-pointer items-center justify-center')
        ->not->toContain('text-[11px] leading-tight font-medium')
        ->toContain("value: 'rounded-lg'")
        ->toContain("value: 'rounded-xl'")
        ->toContain("value: 'rounded-full'")
        ->toContain('Full rounded')
        ->toContain('Space after title')
        ->toContain('Card padding')
        ->toContain('Controls the card padding')
        ->not->toContain('<ToggleGroup')
        ->toContain('value="right"')
        ->toContain('Success heading')
        ->toContain('form.data.success_heading')
        ->toContain('Manage audience fields')
        ->toContain('if (!event.defaultPrevented)')
        ->toContain('router.visit(')
        ->not->toContain('href={audienceAttributes')
        ->toContain('Visibility, requirements, and order')
        ->toContain('data-test="unsaved-changes"')
        ->toContain("'Save & publish'")
        ->toContain("window.confirm('Discard your unsaved form changes?')")
        ->toContain("window.addEventListener('beforeunload', warnBeforeUnload)")
        ->toContain('submitForm(true)')
        ->toContain('publish: publishAfterSave')
        ->toContain('<TabsList')
        ->toContain('variant="sliding"')
        ->toContain('<TabsTrigger')
        ->toContain('form.post(update.form(routeArgs).action')
        ->toContain('const savedData = {')
        ->toContain(
            "const usesArtwork =\n        form.data.style === 'split' || form.data.style === 'cover';",
        )
        ->toContain(
            "form.data.artwork_type === 'upload' &&",
        )
        ->toContain(
            "usesArtwork && data.artwork_type === 'upload'",
        )
        ->toContain('remove_image: usesArtwork && data.remove_image,')
        ->toContain('if (!usesArtwork) {')
        ->toContain('setImagePreview(undefined)')
        ->toContain(
            'const handleStyleChange = (style: SubscribeFormStyle) => {',
        )
        ->toContain("if (style === 'split' || style === 'cover') {")
        ->toContain("form.clearErrors('image')")
        ->toContain('handleStyleChange(')
        ->toContain('{usesArtwork && (')
        ->toContain('form.setData(savedData)')
        ->toContain('form.setDefaults(savedData)')
        ->toContain('data-test="save-subscribe-form"');

    expect($view)->toBeString()
        ->toContain("form.style === 'split'")
        ->toContain("previewViewport === 'mobile'")
        ->toContain("form.style === 'minimal'")
        ->toContain("form.style === 'cover'")
        ->toContain("'data-subscribe-form-theme': ''")
        ->toContain('form.attributes.map((attribute) =>')
        ->toContain("form.first_name_mode === 'optional'")
        ->toContain("form.last_name_mode === 'optional'")
        ->toContain('!attribute.required && <Badge>Optional</Badge>')
        ->toContain('<Badge>Optional</Badge>')
        ->not->toContain("' (optional)'")
        ->toContain('required={!preview && attribute.required}')
        ->toContain("attribute.type === 'date'")
        ->toContain('AttributeDatePicker')
        ->toContain('<Calendar')
        ->toContain("'Pick a date'")
        ->not->toContain('form.data.first_name_mode')
        ->not->toContain('form.data.last_name_mode')
        ->not->toContain('These audience fields are shown on the hosted form.')
        ->toContain('data-test="subscribe-form-logo"')
        ->toContain("data-has-value={selectedDate ? '' : undefined}")
        ->toContain('pointer-events-none sticky top-0 z-0')
        ->toContain('preview={preview}')
        ->toContain('h-[calc(100dvh-7rem)]')
        ->toContain("'sticky top-0 h-svh self-start'")
        ->toContain("form.artwork_type !== 'upload'")
        ->toContain('<SubscribeFormArtworkVisual')
        ->toContain('relative z-10 col-start-1 row-start-1')
        ->toContain('<FormIntro {...intro} as="heading" />')
        ->toContain('<FormIntro {...intro} as="card" />')
        ->not->toContain('logoAlign')
        ->toContain('textAlignmentClasses[form.text_alignment]')
        ->toContain('logoPositionClasses[form.logo_position]')
        ->toContain('headerSpacingClasses[spacing]')
        ->toContain('cardPaddingClasses[form.card_padding]')
        ->toContain('fieldSpacingClasses[form.card_padding]')
        ->toContain("compact: 'gap-4'")
        ->toContain("default: 'gap-5'")
        ->toContain("spacious: 'gap-7'")
        ->toContain("'rounded-full': 'rounded-full object-cover'")
        ->toContain('form.success_heading')
        ->toContain('const title = completed')
        ->toContain('? form.success_heading')
        ->toContain("key={completed ? 'success' : 'form'}")
        ->toContain('successAlignmentClasses[form.text_alignment]')
        ->toContain('function SuccessMark(')
        ->toContain('completed && successAlignmentClasses[form.text_alignment]')
        ->toContain('function CollapsingFields(')
        ->toContain('grid-rows-[0fr]')
        ->toContain('grid-rows-[1fr]')
        ->toContain('<AnimatePresence initial={false} mode="popLayout">')
        ->not->toContain('MORPH_TRANSITION')
        ->not->toContain('MotionCard')
        ->not->toContain('mode="wait"')
        ->toContain('data-test="subscribe-form-morph"')
        ->toContain('data-test="subscribe-form-success"')
        ->toContain('data-test="subscribe-form-powered-by"')
        ->toContain('poweredByAlignmentClasses[position]')
        ->toContain('enabled={!completed}')
        ->toContain('outsideCard')
        ->toContain('variant="cover"')
        ->toContain("'mb-6'")
        ->toContain("'mt-6'")
        ->toContain("'border-white/25 bg-white/10 text-white")
        ->toContain('Redirecting in {redirectCountdown}')
        ->not->toContain('border-primary/20 bg-primary/5')
        ->not->toContain('layoutId=')
        ->not->toContain('CheckmarkCircle02Icon')
        ->toContain('text-xl font-semibold tracking-tight')
        ->toContain('placeholder="email@example.com"')
        ->toContain('data-test="subscribe-form-submit-error"');

    expect($public)->toBeString()
        ->toContain('SubscribeFormView')
        ->toContain('setRedirectCountdown(5)')
        ->toContain('window.location.assign(subscribeForm.redirect_url)')
        ->toContain('onHttpException')
        ->toContain('Too many attempts. Please try again later.')
        ->toContain('submitError ? { form: submitError }');

    expect($edit)->toBeString()
        ->toContain('testId="subscribe-form-section-powered-by"')
        ->toContain('testId="subscribe-form-powered-by-form-position"')
        ->not->toContain('data-test="subscribe-form-powered-by-enabled"')
        ->not->toContain('subscribe-form-powered-by-success-position');

    expect($artwork)->toBeString()
        ->toContain('../../../components/originkit/ui/hero-26/dotmatrix')
        ->toContain('brandArtworkColors[theme.color]')
        ->toContain("'image-aurora'")
        ->toContain("'image-drift'")
        ->toContain("'image-flare'")
        ->toContain("url('/assets/img/subscribe-form-presets/halo.webp')")
        ->toContain("url('/assets/img/subscribe-form-presets/flare.webp')")
        ->toContain("preset === 'background-grid'")
        ->toContain("preset === 'background-orbit'")
        ->toContain("preset === 'background-glow'")
        ->toContain('data-artwork-animation="originkit-hero-26"')
        ->toContain('<DottedBackground')
        ->toContain('createArtworkPalette(primary)')
        ->toContain('linear-gradient(145deg,')
        ->toContain('linear-gradient(to bottom,')
        ->toContain('bgColor="transparent"')
        ->toContain('palette.highlight')
        ->toContain('data-artwork-preset={preset}');

    expect($originKitDotMatrix)->toBeString()
        ->toContain("from 'ogl'")
        ->toContain("matchMedia('(prefers-reduced-motion: reduce)')")
        ->toContain('requestAnimationFrame(update)');
});
