<?php

test('subscribe form editor uses a right inspector and style picker', function () {
    $edit = file_get_contents(dirname(__DIR__, 2).'/resources/js/pages/subscribe-forms/edit.tsx');
    $view = file_get_contents(dirname(__DIR__, 2).'/resources/js/components/subscribe-form-view.tsx');
    $public = file_get_contents(dirname(__DIR__, 2).'/resources/js/pages/subscribe-forms/public.tsx');

    expect($edit)->toBeString()
        ->toContain('lg:border-l')
        ->toContain('lg:w-[26rem]')
        ->toContain('h-dvh')
        ->toContain('ArrowLeft01Icon')
        ->toContain('Back to ${audience.name}')
        ->not->toContain('SubscribeFormEditorLayout')
        ->toContain('lg:overflow-y-auto')
        ->toContain('className="p-4 sm:p-5"')
        ->toContain('justify-between gap-3 border-b bg-background')
        ->toContain('id="subscribe-form-editor"')
        ->toContain('form="subscribe-form-editor"')
        ->toContain('data-test="subscribe-form-actions"')
        ->toContain('data-test="subscribe-form-status"')
        ->not->toContain('sticky bottom-0 z-10 flex justify-end border-t bg-background')
        ->toContain('min-h-[36rem]')
        ->toContain('data-test="subscribe-form-preview"')
        ->toContain('lg:overflow-y-auto')
        ->toContain(
            'lg:max-w-none lg:overflow-y-auto lg:rounded-none lg:border-0 lg:shadow-none',
        )
        ->toContain('data-test={`subscribe-form-style-${option.value}`}')
        ->toContain('<RadioGroup')
        ->toContain('<Radio.Root')
        ->toContain('placeholder="Join our newsletter"')
        ->toContain('placeholder="Website footer"')
        ->toContain('color: form.data.brand_color')
        ->toContain('font: form.data.brand_font')
        ->toContain('form.data.brand_input_style')
        ->toContain('data-test="subscribe-form-brand-color"')
        ->toContain('data-test="subscribe-form-brand-font"')
        ->toContain('data-test="subscribe-form-brand-input-style"')
        ->toContain('function InspectorSection({')
        ->toContain('<Collapsible')
        ->toContain('<CollapsibleTrigger')
        ->toContain('<CollapsibleContent')
        ->toContain('const [open, setOpen] = useState(true);')
        ->toContain('<FieldGroup className="gap-3">')
        ->toContain('className="w-full rounded-xl border bg-card shadow-xs"')
        ->toContain('rounded-lg bg-background shadow-xs ring-1 ring-border')
        ->toContain('testId="subscribe-form-section-layout"')
        ->toContain('testId="subscribe-form-section-brand-theme"')
        ->toContain('testId="subscribe-form-section-artwork"')
        ->toContain('testId="subscribe-form-section-logo"')
        ->toContain('testId="subscribe-form-section-content"')
        ->toContain('data-test="subscribe-form-image-input"')
        ->toContain('const SUBSCRIBE_FORM_IMAGE_MAX_BYTES = 2 * 1024 * 1024;')
        ->toContain('file.size > SUBSCRIBE_FORM_IMAGE_MAX_BYTES')
        ->toContain("form.setError('image', 'Artwork must be 2 MB or smaller.')")
        ->toContain("form.setError('logo', 'Logo must be 2 MB or smaller.')")
        ->toContain('JPG, PNG, or WEBP up to 2 MB.')
        ->toContain('subscribeForm.image_processing')
        ->toContain('optimize uploads to WebP in the')
        ->toContain('usePoll(')
        ->toContain('data-test="subscribe-form-logo-input"')
        ->toContain('data-test="subscribe-form-logo-shape"')
        ->toContain('data-test="subscribe-form-logo-size"')
        ->toContain('data-test="subscribe-form-image-side"')
        ->toContain('data-test="subscribe-form-text-alignment"')
        ->not->toContain('<ToggleGroup')
        ->toContain('value="right"')
        ->toContain('Success heading')
        ->toContain('form.data.success_heading')
        ->toContain('<TabsList')
        ->toContain('variant="sliding"')
        ->toContain('<TabsTrigger')
        ->toContain('form.post(update.form(routeArgs).action')
        ->toContain('const savedData = {')
        ->toContain(
            "const usesArtwork =\n        form.data.style === 'split' || form.data.style === 'cover';",
        )
        ->toContain(
            'const hasImageUpload = usesArtwork && form.data.image !== null;',
        )
        ->toContain(
            'image: usesArtwork ? (data.image ?? undefined) : undefined,',
        )
        ->toContain('remove_image: usesArtwork && data.remove_image,')
        ->toContain('if (!usesArtwork) {')
        ->toContain('setImagePreview(undefined)')
        ->toContain(
            'const handleStyleChange = (style: SubscribeFormStyle) => {',
        )
        ->toContain("if (style === 'split' || style === 'cover') {")
        ->toContain("form.clearErrors('image')")
        ->toContain('handleStyleChange(')
        ->toContain('{usesArtwork && (')
        ->toContain('form.setData(savedData)')
        ->toContain('form.setDefaults(savedData)')
        ->toContain('data-test="save-subscribe-form"');

    expect($view)->toBeString()
        ->toContain("form.style === 'split'")
        ->toContain("form.style === 'minimal'")
        ->toContain("form.style === 'cover'")
        ->toContain("'data-subscribe-form-theme': ''")
        ->toContain('form.attributes.map((attribute) =>')
        ->toContain("form.first_name_mode === 'optional'")
        ->toContain("form.last_name_mode === 'optional'")
        ->toContain('!attribute.required && <Badge>Optional</Badge>')
        ->toContain('<Badge>Optional</Badge>')
        ->not->toContain("' (optional)'")
        ->toContain('required={!preview && attribute.required}')
        ->toContain("attribute.type === 'date'")
        ->toContain('AttributeDatePicker')
        ->toContain('<Calendar')
        ->toContain("'Pick a date'")
        ->not->toContain('form.data.first_name_mode')
        ->not->toContain('form.data.last_name_mode')
        ->not->toContain('These audience fields are shown on the hosted form.')
        ->toContain('<Card className="w-full max-w-md">')
        ->toContain('data-test="subscribe-form-logo"')
        ->toContain('pointer-events-none absolute inset-0 z-0 min-h-full')
        ->toContain('relative z-10 w-full max-w-md')
        ->toContain('<FormIntro form={form} logoAlign="start" as="heading" />')
        ->toContain('<FormIntro form={form} logoAlign="center" as="heading" />')
        ->toContain('<FormIntro form={form} logoAlign="center" as="card" />')
        ->toContain('textAlignmentClasses[form.text_alignment]')
        ->toContain('form.success_heading')
        ->toContain('placeholder="email@example.com"');

    expect($public)->toBeString()
        ->toContain('SubscribeFormView');
});
